-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B1.CATEGORY, SUM(B1.PRICE*B2.SALES) AS TOTAL_SALES 
FROM BOOK AS B1
JOIN AUTHOR AS A ON B1.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES AS B2 ON B1.BOOK_ID = B2.BOOK_ID
WHERE YEAR(B2.sales_date) = 2022 AND MONTH(B2.sales_date) = 01
GROUP BY A.AUTHOR_ID, B1.category
ORDER BY A.AUTHOR_ID, B1.CATEGORY DESC
