-- review
SELECT B.AUTHOR_ID, B.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES*B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES AS S
    LEFT JOIN (
        SELECT B0.BOOK_ID, B0.CATEGORY, B0.AUTHOR_ID, B0.PRICE, A.AUTHOR_NAME
        FROM BOOK AS B0 LEFT JOIN AUTHOR AS A ON B0.AUTHOR_ID=A.AUTHOR_ID) AS B
    ON S.BOOK_ID=B.BOOK_ID
WHERE YEAR(S.SALES_DATE)=2022 AND MONTH(S.SALES_DATE)=01
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC
