SELECT ITEM_ID, ITEM_NAME
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT DISTINCT(T2.ITEM_ID)
    FROM ITEM_TREE T1 JOIN ITEM_TREE T2
    ON T1.PARENT_ITEM_ID=T2.ITEM_ID
    WHERE T2.PARENT_ITEM_ID IS NULL)
ORDER BY ITEM_ID