-- review
SELECT T.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_TREE AS T JOIN ITEM_INFO AS I
    ON T.ITEM_ID = I.ITEM_ID
WHERE T.ITEM_ID NOT IN (
                    SELECT DISTINCT(PARENT_ITEM_ID)
                    FROM ITEM_TREE 
                    WHERE PARENT_ITEM_ID IS NOT NULL
                    )
ORDER BY ITEM_ID DESC