-- 코드를 입력하세요
SELECT 
    U.USER_ID,
    U.NICKNAME,
    CONCAT(U.CITY,' ', U.STREET_ADDRESS1, ' ',U.STREET_ADDRESS2) AS '전체주소',
    CONCAT(LEFT(U.TLNO,3),'-', RIGHT(LEFT(U.TLNO,7),4), '-', RIGHT(U.TLNO,4)) AS '전화번호'
FROM USED_GOODS_BOARD AS B LEFT JOIN USED_GOODS_USER AS U
    ON B.WRITER_ID=U.USER_ID
GROUP BY B.WRITER_ID
HAVING COUNT(B.WRITER_ID)>=3
ORDER BY U.USER_ID DESC