# -- 코드를 입력하세요
# SELECT B.REST_ID, B.REST_NAME, B.FOOD_TYPE, B.FAVORITES, B.ADDRESS, ROUND(AVG(A.REVIEW_SCORE),2) AS SCORE
# FROM REST_REVIEW A JOIN REST_INFO B ON A.REST_ID = B.REST_ID
# WHERE B.ADDRESS LIKE '%서울%' AND REVIEW_SCORE IS NOT NULL
# GROUP BY A.REST_ID
# ORDER BY ROUND(AVG(A.REVIEW_SCORE),2) DESC, FAVORITES DESC

SELECT r.REST_ID
, r.REST_NAME
, r.FOOD_TYPE
, r.FAVORITES
, r.ADDRESS
, ROUND(AVG(y.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS r

LEFT JOIN REST_REVIEW AS y ON r.REST_ID = y.REST_ID

WHERE ADDRESS LIKE '서울%' AND REVIEW_SCORE IS NOT NULL

GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC