SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, U.GENDER, COUNT(DISTINCT(U.USER_ID)) AS USERS
FROM ONLINE_SALE S LEFT JOIN USER_INFO U
    ON S.USER_ID=U.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), U.GENDER
ORDER BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), U.GENDER, COUNT(*)