SET @HOUR=-1
;

SELECT (@HOUR := @HOUR + 1) AS HOUR,
    (SELECT COUNT(ANIMAL_ID)
     FROM ANIMAL_OUTS
     WHERE HOUR(DATETIME) = @HOUR ) AS COUNT
FROM ANIMAL_OUTS
WHERE @HOUR<23
;


#SET 활용법 익히기
#변수 대입 시 := 사용