-- 코드를 입력하세요
SELECT T2.USER_ID,T2.NICKNAME, T1.TOTAL_SALES
FROM (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD 
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    ) AS T1
    LEFT JOIN USED_GOODS_USER AS T2
    ON T1.WRITER_ID = T2.USER_ID
WHERE T1.TOTAL_SALES>=700000
ORDER BY T1.TOTAL_SALES