-- 코드를 입력하세요
SELECT MONTH(C1.START_DATE) AS MONTH, C1.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C1
JOIN (
    SELECT CAR_ID, COUNT(*) AS CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) IN (8, 9, 10)
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) AS C2
ON C1.CAR_ID = C2.CAR_ID
WHERE MONTH(C1.START_DATE) IN (8, 9, 10)
GROUP BY MONTH(C1.START_DATE), C1.CAR_ID
ORDER BY MONTH(C1.START_DATE), C1.CAR_ID DESC;