SELECT 
    YEAR(T1.DIFFERENTIATION_DATE) AS YEAR, 
    T2.MAX_SIZE-T1.SIZE_OF_COLONY AS YEAR_DEV, 
    T1.ID
FROM ECOLI_DATA AS T1 
LEFT JOIN 
    (
    SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS year
    FROM ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) AS T2
ON YEAR(T1.DIFFERENTIATION_DATE) = T2.year
ORDER BY YEAR, YEAR_DEV