SELECT F1.ID, N.FISH_NAME, MAX_LENGTH AS LENGTH
FROM FISH_INFO AS F1
JOIN (
    SELECT I.FISH_TYPE, MAX(I.LENGTH) AS MAX_LENGTH
    FROM FISH_INFO AS I
    GROUP BY I.FISH_TYPE
) AS F2
ON F1.FISH_TYPE = F2.FISH_TYPE AND F1.LENGTH = F2.MAX_LENGTH
JOIN FISH_NAME_INFO AS N
ON F1.FISH_TYPE = N.FISH_TYPE
